# Generated by Django 5.2.6 on 2025-09-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='perfil',
            name='instagram',
            field=models.CharField(blank=True, help_text='Opcional: tu usuario de Instagram', max_length=50, null=True, verbose_name='Instagram'),
        ),
    ]
