# Generated by Django 5.2.6 on 2025-09-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='canchas/'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='precio_por_hora',
            field=models.CharField(help_text='Precio en CLP por 1 hora, ejemplo: $25.000', max_length=20),
        ),
    ]
